<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Client-side components used for CODE Framework Service Features</Description>
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
	</PropertyGroup>

	<ItemGroup>
		<None Include="CODEFrameworkLogoSmall.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
		<Optimize>false</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CODE.Framework.Fundamentals\CODE.Framework.Fundamentals.csproj" />
		<ProjectReference Include="..\CODE.Framework.Services.Contracts\CODE.Framework.Services.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="CodeFramework_Small.png" Pack="true" Visible="false" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
	</ItemGroup>

</Project>
